-- ========================================================================
-- เพิ่มตารางผู้ใช้สำหรับระบบ login / จัดการผู้ใช้
-- รันครั้งเดียวใน Supabase Dashboard > SQL Editor
-- เป็นการ "เพิ่ม" ตารางใหม่เท่านั้น ไม่แตะตารางเดิม ข้อมูลเดิมไม่หาย
-- ========================================================================

CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ใส่บัญชีเริ่มต้น (ถ้ามีชื่อซ้ำจะข้ามให้ ไม่ทับของเดิม)
INSERT INTO app_users (username, password, role, name) VALUES
    ('admin', 'admin123', 'admin', 'ผู้ดูแลระบบ'),
    ('user',  'user123',  'user',  'ผู้ใช้งาน')
ON CONFLICT (username) DO NOTHING;

-- หมายเหตุความปลอดภัย:
-- ตารางนี้เก็บรหัสผ่านแบบ plaintext และเข้าถึงได้ด้วย anon key (เหมือนตารางอื่นในโปรเจคนี้)
-- เหมาะกับงานภายใน/ทีมเล็ก ถ้าต้องการความปลอดภัยจริงจังควรย้ายไปใช้ Supabase Auth + RLS
