-- 1. Create Categories table
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    department TEXT NOT NULL, -- 'ช่างไฟ' หรือ 'ช่างก่อสร้าง'
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create Sites table
CREATE TABLE sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create Tools table
CREATE TABLE tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_code TEXT UNIQUE, -- รหัสเครื่องมือห้ามซ้ำ
    name TEXT NOT NULL,
    department TEXT NOT NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    image_url TEXT,
    total_stock INT DEFAULT 0,
    available_stock INT DEFAULT 0,
    current_site_id BIGINT REFERENCES sites(id) ON DELETE SET NULL,
    current_user_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Create Transactions table
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_id BIGINT REFERENCES tools(id) ON DELETE CASCADE,
    site_id BIGINT REFERENCES sites(id) ON DELETE SET NULL,
    user_name TEXT NOT NULL, -- ชื่อผู้เบิก/คืน
    receiver_name TEXT, -- ชื่อผู้ให้เบิก/รับคืน
    type TEXT CHECK (type IN ('BORROW', 'RETURN')),
    quantity INT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- NOTE: You need to create 'tool-images' and 'category-images' buckets in Supabase Storage 
-- and set them to 'Public' for image uploads to work.
